apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgadmin4.fullname" . }}
  labels:
    app: {{ template "pgadmin4.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  pgadmin4-password:  {{ .Values.pgadmin4.default.password | b64enc | quote }}
