apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pgadmin4.fullname" . }}
  labels:
    app: {{ template "pgadmin4.name" . }}
    chart: {{ template "pgadmin4.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pgadmin4.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pgadmin4.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: {{ .Values.pgadmin4.default.email }}
        - name: PGADMIN_DEFAULT_PASSWORD
          value: {{ .Values.pgadmin4.default.password }}
        name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
